# 使用 Node 20 作爲映像
FROM node:20

# 設置工作目錄
WORKDIR /app

# 將 package.json 和 package-lock.json 複製到容器中
COPY package*.json ./

# 安裝依賴
RUN npm install

# 將項目文件複製到容器中
COPY . .

# 編譯和打包前端應用
COPY dist/ ./

# 暴露端口
EXPOSE 3000

# 定義運行命令
CMD ["npm", "run", "dev"]